# Authorization and Security
admin_login:
    path:     /admin/login
    defaults: { _controller: AdminBundle:Security:login }

admin_logout:
    path:     /admin/logout
    defaults: { _controller: AdminBundle:Security:logout }

admin_auth:
    path:     /admin/auth
    defaults: { _controller: AdminBundle:Security:check }

# Administration
admin_dashboard:
    path:     /{_locale}/admin/dashboard
    defaults: { _controller: AdminBundle:Dashboard:index }
    requirements:
        _locale: en|sr|ru
# Page
admin_page:
    path:     /{_locale}/admin/page
    defaults: { _controller: AdminBundle:Page:index }
    requirements:
        _locale: en|sr|ru

admin_page_create:
    path:     /{_locale}/admin/page/create
    defaults: { _controller: AdminBundle:Page:create }

# User
admin_user:
    path:     /{_locale}/admin/user
    defaults: { _controller: AdminBundle:User:index }
    options:
        expose: true
    requirements:
        _locale: en|sr|ru

admin_user_create:
    path:     /{_locale}/admin/user/create
    defaults: { _controller: AdminBundle:User:create }

admin_user_edit:
    path:     /{_locale}/admin/user/edit/id/{id}
    defaults: { _controller: AdminBundle:User:edit }
    requirements:
        _locale: en|sr|ru

admin_user_modify:
    path:     /admin/user/modify/id/{id}/status/{status}
    defaults: { _controller: AdminBundle:User:modify }
    options:
        expose: true