# Authorization and Security
admin_login:
    path:     /admin/login
    defaults: { _controller: AdminBundle:Security:login }

admin_logout:
    path:     /admin/logout
    defaults: { _controller: AdminBundle:Security:logout }

admin_auth:
    path:     /admin/auth
    defaults: { _controller: AdminBundle:Security:check }

# Administration
admin_dashboard:
    path:     /admin/dashboard
    defaults: { _controller: AdminBundle:Dashboard:index }

# Page
admin_page:
    path:     /admin/page
    defaults: { _controller: AdminBundle:Page:index }
    options:
        expose: true

admin_page_create:
    path:     /admin/page/create
    defaults: { _controller: AdminBundle:Page:create }

admin_page_edit:
    path:     /admin/page/edit/id/{id}/lang/{lang}/
    defaults: { _controller: AdminBundle:Page:edit }

admin_page_translate:
    path:     /admin/page/translate/id/{id}/lang/{lang}/
    defaults: { _controller: AdminBundle:Page:translate }
    requirements:
        lang:  '%app.router_languages%'

admin_page_modify:
    path:     /admin/page/modify/id/{id}/status/{status}
    defaults: { _controller: AdminBundle:Page:modify }
    options:
        expose: true

# Category
admin_category:
    path:     /admin/category
    defaults: { _controller: AdminBundle:Category:index }
    options:
        expose: true

admin_category_edit:
    path:     /admin/category/edit/id/{id}/lang/{lang}/
    defaults: { _controller: AdminBundle:Category:edit }

admin_category_translate:
    path:     /admin/category/translate/id/{id}/lang/{lang}/
    defaults: { _controller: AdminBundle:Category:translate }
    requirements:
        lang:  '%app.router_languages%'

admin_category_modify:
    path:     /admin/category/modify/id/{id}/status/{status}
    defaults: { _controller: AdminBundle:Category:modify }
    options:
        expose: true

admin_category_create:
    path:     /admin/category/create
    defaults: { _controller: AdminBundle:Category:create }

# Subcategory
admin_subcategory:
    path:     /admin/subcategory/parent/{parentId}
    defaults: { _controller: AdminBundle:Category:subindex }

admin_subcategory_create:
    path:     /admin/subcategory/create/parent/{parentId}
    defaults: { _controller: AdminBundle:Category:subcreate }

admin_subcategory_edit:
    path:     /admin/subcategory/edit/id/{id}/lang/{lang}/
    defaults: { _controller: AdminBundle:Category:subedit }

admin_subcategory_translate:
    path:     /admin/subcategory/translate/id/{id}/lang/{lang}/
    defaults: { _controller: AdminBundle:Category:subtranslate }
    requirements:
        lang:  '%app.router_languages%'

# Tag
admin_tag:
    path:     /admin/tag
    defaults: { _controller: AdminBundle:Tag:index }

# User
admin_user:
    path:     /admin/user
    defaults: { _controller: AdminBundle:User:index }
    options:
        expose: true
    requirements:
        _locale: '%app.router_languages%'

admin_user_create:
    path:     /admin/user/create
    defaults: { _controller: AdminBundle:User:create }

admin_user_edit:
    path:     /admin/user/edit/id/{id}
    defaults: { _controller: AdminBundle:User:edit }

admin_user_modify:
    path:     /admin/user/modify/id/{id}/status/{status}
    defaults: { _controller: AdminBundle:User:modify }
    options:
        expose: true
