# Authorization and Security
admin_login:
    path:     /admin/login
    defaults: { _controller: AdminBundle:Security:login }

admin_logout:
    path:     /admin/logout
    defaults: { _controller: AdminBundle:Security:logout }

admin_auth:
    path:     /admin/auth
    defaults: { _controller: AdminBundle:Security:check }

# Administration
admin_dashboard:
    path:     /admin/dashboard
    defaults: { _controller: AdminBundle:Dashboard:index }

# Page
admin_page:
    path:     /admin/page
    defaults: { _controller: AdminBundle:Page:index }
    options:
        expose: true

admin_page_create:
    path:     /admin/page/create
    defaults: { _controller: AdminBundle:Page:create }

admin_page_edit:
    path:     /admin/page/edit/id/{id}/lang/{lang}/
    defaults: { _controller: AdminBundle:Page:edit }

admin_page_translate:
    path:     /admin/page/translate/id/{id}/lang/{lang}/
    defaults: { _controller: AdminBundle:Page:translate }
    requirements:
        lang:  '%app.router_languages%'

admin_page_modify:
    path:     /admin/page/modify/id/{id}/status/{status}
    defaults: { _controller: AdminBundle:Page:modify }
    options:
        expose: true

# Category
admin_category:
    path:     /admin/category
    defaults: { _controller: AdminBundle:Category:index }
    options:
        expose: true

admin_category_edit:
    path:     /admin/category/edit/id/{id}/lang/{lang}/
    defaults: { _controller: AdminBundle:Category:edit }

admin_category_translate:
    path:     /admin/category/translate/id/{id}/lang/{lang}/
    defaults: { _controller: AdminBundle:Category:translate }
    requirements:
        lang:  '%app.router_languages%'

admin_category_modify:
    path:     /admin/category/modify/id/{id}/status/{status}
    defaults: { _controller: AdminBundle:Category:modify }
    options:
        expose: true

admin_category_create:
    path:     /admin/category/create
    defaults: { _controller: AdminBundle:Category:create }

# Subcategory
admin_subcategory:
    path:     /admin/subcategory/parent/{parentId}
    defaults: { _controller: AdminBundle:Category:subindex }

admin_subcategory_create:
    path:     /admin/subcategory/create/parent/{parentId}
    defaults: { _controller: AdminBundle:Category:subcreate }

admin_subcategory_edit:
    path:     /admin/subcategory/edit/id/{id}/lang/{lang}/
    defaults: { _controller: AdminBundle:Category:subedit }

admin_subcategory_translate:
    path:     /admin/subcategory/translate/id/{id}/lang/{lang}/
    defaults: { _controller: AdminBundle:Category:subtranslate }
    requirements:
        lang:  '%app.router_languages%'

# Tag
admin_tag:
    path:     /admin/tag
    defaults: { _controller: AdminBundle:Tag:index }
    options:
        expose: true

admin_tag_create:
    path:     /admin/tag/create
    defaults: { _controller: AdminBundle:Tag:create }

admin_tag_edit:
    path:     /admin/tag/edit/id/{id}/lang/{lang}/
    defaults: { _controller: AdminBundle:Tag:edit }

admin_tag_translate:
    path:     /admin/tag/translate/id/{id}/lang/{lang}/
    defaults: { _controller: AdminBundle:Tag:translate }
    requirements:
        lang:  '%app.router_languages%'

admin_tag_modify:
    path:     /admin/tag/modify/id/{id}/status/{status}
    defaults: { _controller: AdminBundle:Tag:modify }
    options:
        expose: true

# Country
admin_country:
    path:     /admin/country
    defaults: { _controller: AdminBundle:Country:index }
    options:
        expose: true

admin_country_create:
    path:     /admin/country/create
    defaults: { _controller: AdminBundle:Country:create }

admin_country_edit:
    path:     /admin/country/edit/id/{id}/lang/{lang}/
    defaults: { _controller: AdminBundle:Country:edit }

admin_country_translate:
    path:     /admin/country/translate/id/{id}/lang/{lang}/
    defaults: { _controller: AdminBundle:Country:translate }
    requirements:
        lang:  '%app.router_languages%'

admin_country_modify:
    path:     /admin/country/modify/id/{id}/status/{status}
    defaults: { _controller: AdminBundle:Country:modify }
    options:
        expose: true

# Region
admin_region:
    path:     /admin/region
    defaults: { _controller: AdminBundle:Region:index }
    options:
        expose: true

admin_region_create:
    path:     /admin/region/create
    defaults: { _controller: AdminBundle:Region:create }

admin_region_edit:
    path:     /admin/region/edit/id/{id}/lang/{lang}/
    defaults: { _controller: AdminBundle:Region:edit }

admin_region_translate:
    path:     /admin/region/translate/id/{id}/lang/{lang}/
    defaults: { _controller: AdminBundle:Region:translate }
    requirements:
        lang:  '%app.router_languages%'

admin_region_modify:
    path:     /admin/region/modify/id/{id}/status/{status}
    defaults: { _controller: AdminBundle:Region:modify }
    options:
        expose: true

#City
admin_city:
    path:     /admin/city
    defaults: { _controller: AdminBundle:City:index }
    options:
        expose: true

admin_city_create:
    path:     /admin/city/create
    defaults: { _controller: AdminBundle:City:create }

admin_city_edit:
    path:     /admin/city/edit/id/{id}/lang/{lang}/
    defaults: { _controller: AdminBundle:City:edit }

admin_city_translate:
    path:     /admin/city/translate/id/{id}/lang/{lang}/
    defaults: { _controller: AdminBundle:City:translate }
    requirements:
        lang:  '%app.router_languages%'

admin_city_modify:
    path:     /admin/city/modify/id/{id}/status/{status}
    defaults: { _controller: AdminBundle:City:modify }
    options:
        expose: true

#Newsletter
admin_newsletter:
    path:     /admin/newsletter
    defaults: { _controller: AdminBundle:Newsletter:index }
    options:
        expose: true

admin_newsletter_create:
    path:     /admin/newsletter/create
    defaults: { _controller: AdminBundle:Newsletter:create }

admin_newsletter_edit:
    path:     /admin/newsletter/edit/id/{id}
    defaults: { _controller: AdminBundle:Newsletter:edit }

admin_newsletter_modify:
    path:     /admin/newsletter/modify/id/{id}/status/{status}
    defaults: { _controller: AdminBundle:Newsletter:modify }
    options:
        expose: true

# Place
admin_place:
    path:     /admin/place
    defaults: { _controller: AdminBundle:Place:index }
    options:
        expose: true

admin_place_create:
    path:     /admin/newsletter/create
    defaults: { _controller: AdminBundle:Newsletter:create }

admin_place_edit:
    path:     /admin/place/edit/id/{id}/lang/{lang}
    defaults: { _controller: AdminBundle:Place:edit }

admin_place_modify:
    path:     /admin/place/modify/id/{id}/status/{status}
    defaults: { _controller: AdminBundle:Place:modify }
    options:
        expose: true

# User
admin_user:
    path:     /admin/user
    defaults: { _controller: AdminBundle:User:index }
    options:
        expose: true
    requirements:
        _locale: '%app.router_languages%'

admin_user_create:
    path:     /admin/user/create
    defaults: { _controller: AdminBundle:User:create }

admin_user_edit:
    path:     /admin/user/edit/id/{id}
    defaults: { _controller: AdminBundle:User:edit }

admin_user_modify:
    path:     /admin/user/modify/id/{id}/status/{status}
    defaults: { _controller: AdminBundle:User:modify }
    options:
        expose: true
