services:
    html_libraries_extension:
        class: AdminBundle\Twig\HtmlLibrariesExtension
        public: false
        tags: [{ name: twig.extension }]

    sidebar_extension:
        class: AdminBundle\Twig\SidebarExtension
        arguments: ["@request_stack"]
        tags: [{ name: twig.extension }]