parameters:
    property_accessor.class: App\CoreBundle\Form\PropertyAccessor

services:
    sidebar_extension:
        class: AdminBundle\Twig\SidebarExtension
        arguments: ['@request_stack']
        tags: [{ name: twig.extension }]

    # DONT REMOVE THIS, will break all multilanguage forms
    # Read App\CoreBundle\Form\PropertyAccessor class docs for more info
    property_accessor:
        class: '%property_accessor.class%'
        arguments: [true]

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags: [{ name: twig.extension }]

    twig.libraries_extension:
        class: AdminBundle\Twig\LibrariesExtension
        arguments: ['@service_container']
        public: false
        tags: [{ name: twig.extension }]

    # TODO: Make that class construct wait for directory path argument ~
    # TODO: ~ because I'll have thousands of injectors because of file uploading.. Bad :)
    categories_uploader:
        class: App\CoreBundle\Service\Upload\FileUploader
        arguments: ['%categories_directory%']

    cities_uploader:
            class: App\CoreBundle\Service\Upload\FileUploader
            arguments: ['%cities_directory%']