front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

api:
    resource: "@APIBundle/Resources/config/routing.yml"
    prefix:   /
