app_core:
    resource: "@AppCoreBundle/Resources/config/routing.yml"
    prefix:   /

front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

api:
    resource: "@APIBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

my_yaml_i18n_routes:
    resource: "@AdminBundle/Resources/translations/routes/i18n.yml"
    type: be_simple_i18n

oneup_uploader:
    resource: .
    type: uploader