<?php

namespace AdminBundle\Repository;

/**
 * PageContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageContentRepository extends \Doctrine\ORM\EntityRepository
{
}
